DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS food_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  phone_num VARCHAR(32) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE TABLE food_items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  cost INTEGER NOT NULL,
  description TEXT NOT NULL,
  in_stock BOOLEAN NOT NULL,
  food_photo_url TEXT NOT NULL
);
CREATE TABLE orders(
  id SERIAL PRIMARY KEY NOT NULL,
  food_name_qty VARCHAR(255) NOT NULL,
  order_total VARCHAR(255) NOT NULL,
  order_notes VARCHAR(255) NOT NULL,
  order_status VARCHAR(255) NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
